language: php
sudo: false
git:
    depth: 5
    submodules: false
matrix:
    include:
        - php: 7.2

before_install:
    - export FLOW_TARGET_VERSION=6.0
    - cd ..
    - git clone https://github.com/neos/flow-base-distribution.git -b ${FLOW_TARGET_VERSION}
    - cd flow-base-distribution
    - composer require --no-update --no-interaction neos/redirecthandler:4.0.x-dev
    - composer require --no-update --no-interaction neos/redirecthandler-databasestorage:dev-master
install:
    - composer install --no-interaction
    - cd ..
    - rm -rf flow-base-distribution/Packages/Application/Neos.RedirectHandler
    - mv redirecthandler flow-base-distribution/Packages/Application/Neos.RedirectHandler
    - cd flow-base-distribution
script:
    - bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Neos.RedirectHandler/Tests/Unit
    - bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Neos.RedirectHandler/Tests/Functional/*
